SELECT * 
FROM USERS;

SELECT * 
FROM VERIFICATION_TOKEN; 


SELECT *
FROM USERS u , VERIFICATION_TOKEN vt 
WHERE u.ID = vt.USER_ID ;

--DROP TABLE USERS ;
--DROP TABLE VERIFICATION_TOKEN ;

--DELETE FROM  VERIFICATION_TOKEN ;
--DELETE FROM USERS ; 

COMMIT;

show tables;